### ISSUE TITLE
character in a cave fighting against theoretical constructs that look like wisps from WC3

### ISSUE THREAD

**Issue by MeryemA** [ebrahimebrahim/peupfudge#3]
that are invincible and blink out of existence 10 seconds after their birth

**Comment by MeryemA** [comment]
![Peupfudge_wisp_signed](https://user-images.githubusercontent.com/45949775/56719102-0dc92580-670e-11e9-8049-8fec939ceda5.png)

**Comment by Y9ssra** [comment]
Absolutely incredible. Her stance and the wisps themselves and the cave environment, particularly the lighting on the wall (and the lighting in general, which looks insanely good)... I am just in awe, masha'Allah Maryam. I love how the sword interacts with the wisp on the right. I'm also a big fan of her outfit. Simply amazing, and I think you could make a lot of money from your art.

**Comment by ebrahimebrahim** [comment]
This is so amazing! I'm blown away.

Not just the drawing but the decisions about the scene-- including the standing water, the light coming from the opening creating the perfect dramatic lighting, the wispy motion-lines trailing behind the creatures which makes them look unreal and temporary, and the character's stance making it look like an outnumbered or somewhat confused but still determined fighter. It's perfect!

**Comment by MeryemA** [comment]
Awesome, thank you! I'm glad you like it!
