### ISSUE TITLE
someone stabilizing a bleeding person

### ISSUE THREAD

**Issue by Y9ssra** [ebrahimebrahim/peupfudge#5]

**Comment by Y9ssra** [comment]
![image](https://user-images.githubusercontent.com/48895790/55285221-b4134c80-5355-11e9-98c8-786730a1a868.png)

**Comment by ebrahimebrahim** [comment]
It's really good!

Can we try without the gradient background? Remember that this is going to sit inside text on a white page, or on a website with a white background. It would be nice to have those two guys sitting directly on the page rather than inside a frame. 

Could they maybe have some shadows below them to give a feeling of the surface they're on? IDK how hard that is to do, or if it would look better

**Comment by Y9ssra** [comment]
Yes, that should be easy insha'Allah. I'll try it now.

**Comment by Y9ssra** [comment]
![image](https://user-images.githubusercontent.com/48895790/55294715-62a9a280-53d3-11e9-8254-4f82c53e29b3.png)

**Comment by Y9ssra** [comment]
![image](https://user-images.githubusercontent.com/48895790/55296861-39960b80-53ed-11e9-8214-ffa970dcd538.png)

**Comment by Y9ssra** [comment]
Three hours later, I also decided to dilute her bandanna color a bit too, because it was drawing the eye too much and not in harmony with the other colors in the piece.

**Comment by ebrahimebrahim** [comment]
It does look much nicer I think, but there's still a gradient making it have a rectangular frame. If it sits inside a white backgroud, you would get these corners on the bottom. This is fine if it's a full scene being framed in, but it's just the two subjects, so I think it would be better to make them appear without a rectangular frame. 

What I meant by shadows on the floor was that the subjects could cast shadows, not that the floor has shading. But this might be too hard or not make sense with your style so feel free to ignore it.

**Comment by Y9ssra** [comment]
Counterpoint: I think having the picture half-framed is kind of awesome, like a minimalist stylistic choice. Cast shadows, on the other hand, would take too much effort for too little (if any) improvement, I'd say, especially considering this illustration isn't shaded, but colored in the flat style.

**Comment by ebrahimebrahim** [comment]
Good points. I'll wait for yusuf and possibly others to weight in before closing.

**Comment by yusufmte** [comment]
Very nice, looks awesome! As for the gradient I think the current gradient with the white to black is OK.

**Comment by MeryemA** [comment]
Agreed! I think the simple grey half-frame looks best for this piece. Cast shadows or no shadows both seem like lesser options.

**Comment by Y9ssra** [comment]
Thank you everyone! :-)
