### ISSUE TITLE
a character chasing a chicken, with the trajectory indicated with regular distance markings

### ISSUE THREAD

**Issue by leyi-z** [ebrahimebrahim/peupfudge#6]

**Comment by LeyiZ** [comment]
![Uploading Los Pollos Hermanas-sketch.png…]()

**Comment by LeyiZ** [comment]
![Los Pollos Hermanas-sketch](https://user-images.githubusercontent.com/45939916/56935829-8fbba480-6aa8-11e9-9209-fed2a31759db.png)

**Comment by yusufmte** [comment]
Woah, really nice style, I love the background!

**Comment by MeryemA** [comment]
Really nice! The background is awesome and I love the chicken's face!

**Comment by ebrahimebrahim** [comment]
Even with all the changes to peupfudge, this illustration is still relevant. We are likely to reintroduce the old "time and space" section as a module, and then this will be an awesome illustration to have!

**Comment by leyi-z** [comment]
Will probably restart if work on this again.
