### ISSUE TITLE
a guy trying to climb a cliff while dodging falling boulders

### ISSUE THREAD

**Issue by MeryemA** [ebrahimebrahim/peupfudge#7]
Actually probably a girl; let's be honest.

**Comment by MeryemA** [comment]
![ClimbNAvoid](https://user-images.githubusercontent.com/45949775/77236822-6dd38080-6b98-11ea-8eba-d4cf8344ead8.png)

**Comment by ebrahimebrahim** [comment]
Woah really neat concept! Way better than what I was initially imagining.

Hopefully we resume work on peupfudge at some point lol

**Comment by MeryemA** [comment]
Thanks!
Haha everyone's been mighty busy, but insha'Allah soon :D

**Comment by MeryemA** [comment]
![ClimbNAvoidFinal](https://user-images.githubusercontent.com/45949775/77617781-57685480-6f0b-11ea-9e70-9399f71b16eb.png)
I think that's finished!

**Comment by ebrahimebrahim** [comment]
added into the repository

It looks REALLY amazing! Blow away

**Comment by MeryemA** [comment]
Thank you!
