### ISSUE TITLE
a guy climbing an "ability tree"

### ISSUE THREAD

**Issue by MeryemA** [ebrahimebrahim/peupfudge#8]
Yusuf had a cool idea for this, which I'm sure he will explain here in a minute, but it will take 200 years to make. I'll gradually work on it though!

**Comment by yusufmte** [comment]
An Ability Tree manifests in all its glory as a physical tree. Symbols of various abilities are arranged around the leaves and branches of the tree. Off the tip of one branch a bow and full quiver might be hanging, near a saber dangling from the tip of a nearby branch. The node immediately common to these branches might harbor a pair of stag beetles in battle, locked in stalemate. Elsewhere on the tree, there may be a microscope precariously laying across the tip of one branch, near a beaker (containing a curious fluid) on the tip of another nearby. An open book is nestled in the groove of the node uniting these branches. (Or perhaps instead there are characters perched on the branches of the Tree, holding the bow in full draw, pointing the saber out and standing in a fencing stance, peering through the microscope, twirling the beaker-- it's too far to tell for sure from where I'm currently standing.) Branches thick and thin represent various weights-- the strengths of connection between abilities and their relatives. A character ascends the trunk of the Tree, looking up at the scene ahead.

**Comment by ebrahimebrahim** [comment]
Ability trees are no longer a main focus of peupfudge
